version: '3'
services:
  web:
    container_name: nono150_web
    build: ./docker/web
    ports:
      - '80:80'
    volumes:
      - ./apps:/var/www/html
      - ./docker/logs:/var/log/httpd
      - ./docker/web/conf.d/vhosts.conf
      # Add symlink directories if you use symlinks at documents.
      - ~/git:/Users/itigoppo/git
    depends_on:
      - mysql
    # 所属するネットワークとIPを指定
    networks:
      br0:
        ipv4_address: 192.168.202.3

  mysql:
    container_name: nono150_mysql
    build: ./docker/db
    volumes:
      - ./docker/db/data:/var/lib/mysql
    ports:
      - "3306:3306"
    hostname: localhost
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    # 所属するネットワークとIPを指定
    networks:
      br0:
        # このIPアドレスがデータベースホスト名になる ( localhost → 192.168.202.2)
        ipv4_address: 192.168.202.2

# 新規ブリッチを定義
networks:
  br0:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.202.0/24
